apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: keycloak-system
spec:
  secretName: keycloak-tls
  dnsNames:
    - 'host.keycloak.full-coral.cc'
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: keycloak-issuer
