# clusterissuer-lets-encrypt-production.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: j.manjunatha@reply.de
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        azureDNS:
          resourceGroupName: tech-challenge
          subscriptionID: 7b3d4e1a-f9d3-4450-b88e-759cff82af4d
          hostedZoneName: keycloak.full-coral.cc
          environment: AzurePublicCloud
          managedIdentity:
            clientID: bd0a5ef2-1518-46a3-8bac-80e12cb8bbfd