apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SERVER_DOMAIN
              value: grafana.full-coral.cc
            - name: GF_SERVER_ROOT_URL
              value: http://grafana.full-coral.cc
            # - name: GF_SERVER_CERT_KEY
            #   value: /etc/grafana/certs/tls.key
            # - name: GF_SERVER_CERT_FILE
            #   value: /etc/grafana/certs/tls.crt
            # - name: GF_SERVER_PROTOCOL
            #   value: https
            # - name: GF_ENFORCE_DOMAIN
            #   value: "false"
            - name: GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: Keycloak-OAuth
            - name: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              value: grafana-oauth
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              value: qIv6DrJlCS1Xwo32bxK7vylyckNdH71u
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: openid email profile offline_access roles
            - name: GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH
              value: email
            - name: GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH
              value: username
            - name: GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH
              value: full_name
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              value: https://keycloak.full-coral.cc/realms/test/protocol/openid-connect/auth
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: https://keycloak.full-coral.cc/realms/test/protocol/openid-connect/token
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              value: https://keycloak.full-coral.cc/realms/test/protocol/openid-connect/userinfo
            - name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
              value: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            # - mountPath: /etc/grafana/certs
            #   name: grafana-tls
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        # - name: grafana-tls
        #   secret:
        #     secretName: grafana.full-coral.cc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  ports:
    - port: 80
      name: http-grafana
      protocol: TCP
      targetPort: http-grafana
    - port: 443
      name: https-grafana
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer