---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
  ref:
    tag: 22.2.5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: keycloak
    namespace: flux-system
  values:
    replicaCount: 3
    postgresql:
      enabled: false
    externalDatabase:
      host: myexternalhost
      user: myuser
      password: mypassword
      database: mydatabase
      port: 5432