apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: grafana-issuer
  namespace: grafana
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: private-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
